### ISSUE TITLE
InvalidArgumentException not PSR-4 compliant

### ISSUE THREAD

**Issue by UlrichEckhardt** [byjg/cache-engine-php#4]
The exception is in a subdirectory `Exception`, but its namespace doesn't reflect that. I'd move it to the parent folder, since it's the only file anyway and it already has "Exception" in its name. This causes a warning when installing this as dependency in php-swagger-tests with a newer Composer version.

BTW, if you're at it anyway, you could enable testing with PHP 7.4.

Cheers!

Uli

**Comment by byjg** [comment]
Thank you again Uli :)
